#!/bin/bash

set -e

device="$1"
crossflash="$2"

if [ -e run.conf ]; then
    source run.conf
fi

variant="$device"
if [ -n "$crossflash" ]; then
    variant="crossflash-$device"
fi

script="build/lanchon-twrp-patcher-$variant.sh"
./make-script "$device" "$crossflash" "$script"

adb push "$script" /tmp/twrp-patcher.sh
echo

adb shell sh /tmp/twrp-patcher.sh
